# Generated by Django 3.1.2 on 2020-10-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='image_created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
